### ISSUE TITLE
Metamorphic Relations

### ISSUE THREAD

**Issue by bajinsheng** [ZJU-Automated-Reasoning-Group/smtfuzz#1]
Hi, I am reading this paper: https://5hadowblad3.github.io/files/FSE21.pdf. Is the method `Sparrow` described in the paper implemented in the file `example/mutation.py`? If so, what do these modes (cube, quant, domain) in the code mean? I have not found any explanation in the paper. Thanks!

**Comment by rainoftime** [comment]
The metamorphic relations in the paper are not in this repo. 
The examples in `example/mutation.py` are new, and do not preserve equivalence of other MRs.
